# Generated by Django 5.2.12 on 2026-03-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="approximate_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="items_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
