# Generated by Django 5.2.12 on 2026-03-12 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_approximate_weight_booking_items_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Number of pickups that can be scheduled in this slot",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_time_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bookings.timeslot",
            ),
        ),
    ]
