# Generated by Django 5.2.12 on 2026-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_timeslot_alter_booking_pickup_time_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
