# Generated by Django 5.2.12 on 2026-03-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("payout_pending", "Payout Pending"),
                    ("payout_completed", "Payout Completed"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
