# Generated by Django 5.2.12 on 2026-03-06 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("wallet_points", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                (
                    "total_recycled",
                    models.PositiveIntegerField(
                        default=0, help_text="Total items recycled"
                    ),
                ),
                (
                    "co2_saved",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="CO2 saved in kg",
                        max_digits=10,
                    ),
                ),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("preferred_language", models.CharField(default="en", max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
