# Generated by Django 5.2.12 on 2026-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome class or image URL", max_length=100
                    ),
                ),
                (
                    "required_co2_saved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "required_toxic_diverted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="achievements",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="toxic_diverted_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Toxic materials diverted in kg",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="earned_badges",
            field=models.ManyToManyField(
                blank=True, related_name="earned_by", to="accounts.badge"
            ),
        ),
    ]
