# Generated by Django 5.2.12 on 2026-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("company", models.CharField(blank=True, default="", max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("corporate", "Corporate IT Asset Disposal"),
                            ("data", "Data Destruction Service"),
                            ("residential", "Residential Pickup"),
                            ("battery", "Battery Recycling"),
                            ("other", "Other / Multiple Services"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10 items"),
                            ("10-50", "10-50 items"),
                            ("50-200", "50-200 items"),
                            ("200+", "200+ items"),
                            ("bulk", "Bulk / Ongoing requirement"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("is_handled", models.BooleanField(default=False)),
                (
                    "handled_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Request",
                "verbose_name_plural": "Contact Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
