# Generated by Django 5.2.12 on 2026-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=500, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("regulations", "Regulations"),
                            ("security", "Security"),
                            ("sustainability", "Sustainability"),
                            ("safety", "Safety"),
                            ("guides", "Guides"),
                            ("health", "Health"),
                            ("news", "News"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "summary",
                    models.TextField(help_text="Short summary for card display"),
                ),
                ("content", models.TextField(help_text="Full article content (HTML)")),
                ("read_time", models.CharField(default="5 min read", max_length=20)),
                ("published_date", models.DateField()),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
    ]
