# Generated by Django 5.2.12 on 2026-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("address", models.TextField()),
                (
                    "accepts",
                    models.JSONField(
                        default=list, help_text="List of accepted item types"
                    ),
                ),
                ("verified", models.BooleanField(default=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
                ),
                ("contact", models.CharField(blank=True, default="", max_length=50)),
                (
                    "hours",
                    models.CharField(default="9:00 AM - 6:00 PM", max_length=100),
                ),
                (
                    "services",
                    models.JSONField(
                        default=list, help_text="List of services offered"
                    ),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                (
                    "center_type",
                    models.CharField(
                        choices=[
                            ("E-Zero", "E-Zero (Owned)"),
                            ("Partner", "Partner Center"),
                        ],
                        default="E-Zero",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["city", "name"],
            },
        ),
    ]
